# Generated by Django 5.0.6 on 2024-05-20 05:08

from django.db import migrations, models


def populate_products(apps, schema_editor):
    Product = apps.get_model('baykarApp', 'Product')
    Product.objects.create(brand='Baykar', name='Bayraktar Akıncı', price=99.99,
                           image_url='baykarApp/images/baykar_bayraktar_akinci.jpg')
    Product.objects.create(brand='Baykar', name='Bayraktar DİHA', price=149.99,
                           image_url='baykarApp/images/baykar_bayraktar_diha.jpg')
    Product.objects.create(brand='Baykar', name='Bayraktar TB-2', price=249.99,
                           image_url='baykarApp/images/baykar_bayraktar_tb2.jpg')
    Product.objects.create(brand='Baykar', name='Bayraktar TB-3', price=349.99,
                           image_url='baykarApp/images/Baykar_Bayraktar_TB-3.png')


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.RunPython(populate_products)
    ]
