# Generated by Django 5.0.6 on 2024-05-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykarApp', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
